apiVersion: v1
kind: ConfigMap
metadata:
  name: sfdc-cloudgenix-calculated-application-config-map
  namespace: producer 
data:
  sfdc_calculated_application.properties: |-
    spring.jpa.hibernate.ddl-auto=none
    spring.datasource.url=jdbc:mysql://MYSQL_URL/e2e_scheduler_cloudgenix?useSSL=false&&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    spring.datasource.username=${MYSQL_SCHEDULER_USER_NAME}
    spring.datasource.password=${MYSQL_SCHEDULER_PASSWORD}
    spring.datasource.driver-class-name=com.mysql.jdbc.Driver
    spring.datasource.dbcp.test-while-idle=true
    spring.datasource.dbcp.time-between-eviction-runs-millis=3600000
    spring.datasource.dbcp.validation-query=SELECT 1
    spring.datasource.driver-class-name=com.mysql.jdbc.Driver
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
    spring.jpa.properties.hibernate.connection.autoReconnect=true
    spring.jpa.show-sql = true
    gcp.credentials=sfdc.producer.json
    storage.bucket=ite-aia-dp
    sfdc.calaculated.dataset=sfdc_landing_cloudgenix
    sfdc.token.grant_type=password
    sfdc.token.client_id=${SALESFORCE_CLIENT_ID}
    sfdc.token.client_secret=${SALESFORCE_CLIENT_SECRET}
    sfdc.token.username=${SALESFORCE_USER_NAME}
    sfdc.token.password=${SALESFORCE_PASSWORD}
    sfdc.token.url=https://cloudgenix.my.salesforce.com/services/oauth2/token?
    sfdc.job.url=https://cloudgenix.my.salesforce.com/services/async/47.0/job/
    sfdc.job.operation=query
    sfdc.job.contentType=CSV
    sfdc.batch.url=https://cloudgenix.my.salesforce.com/services/async/47.0/job/{0}/batch
    sfdc.batchinfo.url=https://cloudgenix.my.salesforce.com/services/async/47.0/job/{0}/batch/{1}
    sfdc.result.url=https://cloudgenix.my.salesforce.com/services/async/47.0/job/{0}/batch/{1}/result
    sfdc.result.download.url=https://cloudgenix.my.salesforce.com/services/async/47.0/job/{0}/batch/{1}/result/{2}
    sfdc.job.close.url=https://cloudgenix.my.salesforce.com/services/async/47.0/job/{0}
    thread.pool.size=10
    bigquery.project=ite-aia-datalake
    sfdc.landing.dataset=sfdc_landing_cloudgenix
    sfdc.datapipeline.dataset=datapipeline
    sfdc.datapipeline.history.table=cloudgenix_calculated_run_history
    prometheus.metrics.jobname=sfdccalculated_cloudgenix
    management.endpoints.web.exposure.include=prometheus
    management.security.enabled=false
    prometheus.endpoint=prometheus-ite-aia-dp-pushgateway.prometheus.svc:9091/pushgateway